#!/bin/python3
import sys
from os import path, system

app_cache = path.abspath(".cache")
app_config = path.abspath(".config")

filename = path.join(app_cache, "temp.dat")
cmd = "lsb_release -r > "+filename.replace(" ", "\\ ")
system(cmd)

file = open(filename)
file_str = file.read()
file.close()

version_code = file_str.split(":")[1].strip()
print(version_code)

from py.Application import GitCloner

def main():
    app = GitCloner()
    return app.run(sys.argv)

main()